theme: jekyll-theme-cayman
title: "NordConsNet Workshop 2019"
description: "The 18th workshop of [NordConsNet](http://www.it.uu.se/research/NordConsNet), the Nordic Network for researchers and practitioners of Constraint Programming"
